import Link from "next/link";
import Image from "next/image";

const responsibilities = [
  { number: "01", title: "What the LLM does", body: "Four scoped prompts identify candidate revenue, cash-flow, related-party, and communication-pattern issues. A strict second pass classifies only against supplied evidence.", output: "Structured candidates and evidence-bound classifications" },
  { number: "02", title: "What Python does", body: "Python recomputes growth, free cash flow, margins, and direct values using filed inputs and explicit tolerances. Model arithmetic is never authoritative.", output: "Formula, inputs, computed value, gap, and tolerance" },
  { number: "03", title: "What retrieval does", body: "The retrieval stage ranks multiple passages from statements, footnotes, MD&A, policies, segment notes, and reconciliations for each stable finding.", output: "Located candidate passages with source locations" },
  { number: "04", title: "What validation does", body: "Every proposed explanation quote is matched against the filing and checked for a direct relationship. Numerical explanations must bridge the actual gap.", output: "Validated explanation or explained-to-unresolved transition" },
  { number: "05", title: "What the human does", body: "An analyst reviews the complete evidence chain and records accept, reject, or needs-review for every finding. The decision updates the integrity digest.", output: "Per-finding signed decision" },
];

export default function ArchitecturePage() {
  return <main className="architecture-page"><nav className="nav shell"><Link className="brand" href="/"><span>F</span>FinTrace</Link><Link className="text-link" href="/">Back to judge demo</Link><span className="public-pill"><i /> Public fictional demo</span></nav><section className="architecture-hero shell"><p className="eyebrow">System architecture</p><h1>Five roles.<br /><em>One evidence chain.</em></h1><p>Models interpret. Code calculates. Filings provide evidence. Validators verify. Humans decide.</p></section><section className="workflow-figure shell"><Image src="/fintrace-ml-workflow.png" alt="FinTrace workflow from human input through specialist model calls, deterministic Python calculation, filing retrieval, second-pass review, quote validation, and human decision" width={2200} height={1400} priority /></section><section className="responsibility-list shell">{responsibilities.map((item) => <article key={item.number}><span>{item.number}</span><div><h2>{item.title}</h2><p>{item.body}</p></div><aside><small>OUTPUT</small><strong>{item.output}</strong></aside></article>)}</section><section className="architecture-rule"><div className="shell"><p>EXPLAINED requires all four gates</p><div><span>Specific filing evidence</span><b>+</b><span>Direct connection</span><b>+</b><span>Valid quotation</span><b>+</b><span>Numerical reconciliation</span><b>=</b><strong>EXPLAINED</strong></div><small>If any gate fails, the result is UNRESOLVED.</small></div></section><footer className="footer shell"><div className="brand"><span>F</span>FinTrace</div><p>Evidence before interpretation.</p><span>Reverie Hacks 2026</span></footer></main>;
}
